name: Trigger Repo A Workflow

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  trigger-repo-a:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo B
        uses: actions/checkout@v2  # This step is necessary to check out the code

      # - name: Trigger Repo A Workflow using Custom Action
      #   uses: ./.github/actions/trigger-repo-a  # Path to your custom action
      - name: Invoke workflow in another repo with inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
           workflow: SimpleTriggerTest.yml
           repo: MathanRasu/Repo_A
           inputs: '{ "ref": "Test-WorkFlow-RepoA-02" }'
           token: "${{ secrets.REPO_B_PAT_TOKEN }}"
          
          # token: ${{ secrets.REPO_B_PAT_TOKEN }}
          # repo: MathanRasu/Repo_A
          # workflow_file: SimpleTriggerTest.yml
          # ref: Test-WorkFlow-RepoA-02
