name: Workflow_2

on:
  workflow_dispatch:

jobs:
  trigger-repo-a:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Repo A Workflow
        env:
          PAT: ${{ secrets.REPO_B_PAT_TOKEN }} # The secret containing the PAT
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $PAT" \
            https://api.github.com/repos/MathanRasu/Repo_A/actions/workflows/Workflow-Test1-test-Branch.yml/dispatches \
            -d "{\"ref\":\"Test_Workflow_B_01\",\"inputs\":{\"custom_input\":\"Triggered by Repo B\"}}"
