name: Trigger Repo A Workflow with Custom Action

on:
  push:
    branches:
      - main

jobs:
  trigger-repo-a:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Repo A Workflow using Custom Action
        uses: MathanRasu/trigger-repo-a-action@v1.0.0
        with:
          token: ${{ secrets.REPO_B_PAT_TOKEN }}
          repo: MathanRasu/Repo_A
          workflow_file: Test-WorkFlow-RepoA-TestBranch.yml
          ref: Test-WorkFlow-RepoA-02
