name: Trigger Repo A Workflow

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  trigger-repo-a:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo B
        uses: actions/checkout@v2  # This step is necessary to check out the code

      - name: Trigger Repo A Workflow using Custom Action
        uses: ./.github/actions/trigger-repo-a  # Path to your custom action
        with:
          token: ${{ secrets.REPO_B_PAT_TOKEN }}
          repo: MathanRasu/Repo_A
          workflow_file: Test-WorkFlow-RepoA-TestBranch.yml
          ref: Test-WorkFlow-RepoA-02
